"""empty message

Revision ID: 1e2d263031d4
Revises: c0bd68e19b80
Create Date: 2024-05-07 10:42:09.401373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2d263031d4'
down_revision = 'c0bd68e19b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('films')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
